"""
Django settings for crosschain_backend project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from datetime import timedelta
from os import environ
from pathlib import Path

from django.utils import timezone
from kombu import Queue, Exchange

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environ.get('BACKEND_SECRET_KEY')
SECRET_KEY_ID = environ.get('BACKEND_SECRET_KEY_ID')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(environ.get('BACKEND_DEBUG_MODE'))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3RD-PARTY EXTENTIONS
    'corsheaders',
    'django_celery_beat',
    'django_extensions',
    'django_filters',
    'drf_spectacular',
    'rest_framework',
    'rangefilter',
    ###

    # APPS
    'contracts',
    'networks',
    'notifications',
    'trades',
    'tokens',
    'users',
    'validators',
    ###
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crosschain_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crosschain_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': environ.get('DATABASE_NAME'),
        'USER': environ.get('DATABASE_ORIGIN_USER'),
        'PASSWORD': environ.get('DATABASE_ORIGIN_PASS'),
        'HOST': environ.get('DATABASE_HOST'),
        'PORT': environ.get('DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '/code/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

# CACHING
CACHE = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'TIMEOUT': int(environ.get('DEFAULT_CACHE_TIMEOUT')),
        'OPTIONS': {
            # Максимальное количество элементов в кеше.
            'MAX_ENTRIES': int(environ.get('MAX_ENTRIES')),
            # Часть элементов, которые нужно удалить.
            # Вычисляется по формуле: MAX_ENTRIES / CULL_FREQUENCY.
            'CULL_FREQUENCY': int(environ.get('CULL_FREQUENCY')),
        }
    }
}

DEFAULT_VIEW_CACHE_TIMEOUT = int(environ.get('DEFAULT_VIEW_CACHE_TIMEOUT'))

# LOGGING
LOGGING_CURRENT_DATE = timezone.now()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '%(name)-12s %(levelname)-8s %(message)s'
        },
        'file': {
            'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'file',
            'filename': '{mode}_{year}_{month}.log'.format(
                mode=environ.get('BACKEND_SETTINGS_MODE'),
                year=LOGGING_CURRENT_DATE.year,
                month=LOGGING_CURRENT_DATE.month
            )
        }
    },
    'loggers': {
        '': {
            'level': 'DEBUG',
            'handlers': ('console', 'file')
        },
        'django.request': {
            'level': 'DEBUG',
            'handlers': ('console', 'file'),
            'propagate': False
        },
        'django.server': {
            'level': 'DEBUG',
            'handlers': ('console', 'file'),
            'propagate': False
        },
        'crosschain_backend.contracts': {
            'level': 'DEBUG',
            'handlers': ('console', 'file'),
            'propagate': False
        },
        'crosschain_backend.networks': {
            'level': 'DEBUG',
            'handlers': ('console', 'file'),
            'propagate': False
        },
        'crosschain_backend.users': {
            'level': 'DEBUG',
            'handlers': ('console', 'file'),
            'propagate': False
        },
    }
}

# BROKER
BROKER_SERVICE_NAME = environ.get('BROKER_SERVICE_NAME')
BROKER_HOST = environ.get('BROKER_HOST')
BROKER_PORT = environ.get('BROKER_PORT')
BROKER_URL = f'redis://{BROKER_HOST}:{BROKER_PORT}/0'
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600, }

# CELERY
CELERY_DATA_FORMAT = 'json'
CELERY_BROKER_URL = f'redis://{BROKER_SERVICE_NAME}:{BROKER_PORT}/0'
# CELERY_RESULT_BACKEND = f'redis://{BROKER_SERVICE_NAME}:{BROKER_PORT}/0'
CELERY_ACCEPT_CONTENT = [f'application/{CELERY_DATA_FORMAT}', ]
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_SERIALIZER = CELERY_DATA_FORMAT
CELERY_RESULT_SERIALIZER = CELERY_DATA_FORMAT

CELERY_QUEUE_HIGH_NAME = 'high'
CELERY_QUEUE_MIDDLE_NAME = 'middle'
CELERY_QUEUE_LOW_NAME = 'low'

CELERY_QUEUES = (
    Queue(
        CELERY_QUEUE_HIGH_NAME,
        Exchange(CELERY_QUEUE_HIGH_NAME),
        routing_key=CELERY_QUEUE_HIGH_NAME
    ),
    Queue(
        CELERY_QUEUE_MIDDLE_NAME,
        Exchange(CELERY_QUEUE_MIDDLE_NAME),
        routing_key=CELERY_QUEUE_MIDDLE_NAME
    ),
    Queue(
        CELERY_QUEUE_LOW_NAME,
        Exchange(CELERY_QUEUE_LOW_NAME),
        routing_key=CELERY_QUEUE_LOW_NAME
    ),
)
CELERY_DEFAULT_QUEUE = CELERY_QUEUE_MIDDLE_NAME
CELERY_DEFAULT_EXCHANGE = CELERY_QUEUE_MIDDLE_NAME
CELERY_DEFAULT_ROUTING_KEY = CELERY_QUEUE_MIDDLE_NAME
CELERY_ROUTES = {
    'notifications.tasks.send_error_notification_task': {
        'queue': CELERY_QUEUE_MIDDLE_NAME,
    },
}

CELERY_BEAT_SCHEDULE = {
    # SEND SIGNATURE TO RELAYER
    'update_swaps_task': {
        'task': 'validators.tasks.update_swaps_task',
        'schedule': timedelta(seconds=60),
    },
}

CELERYD_HIJACK_ROOT_LOGGER = False
CELERYD_LOG_COLOR = True

CELERYD_PREFETCH_MULTIPLIER = 1
CELERYD_CONCURRENCY = int(environ.get('CELERY_CONCURRENCY', 1))

# DRF_SPECTACULAR
SPECTACULAR_SETTINGS = {
    'TITLE': 'RUBIC CROSSCHAIN API',
    'DESCRIPTION': '',
    'VERSION': '1.0.0',
    # OTHER SETTINGS
    'AUTHENTICATION_WHITELIST': [
        'rest_framework.authentication.BaseAuthentication',
    ],
}

# REST_FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# LOCAL SETTINGS
ALLOWED_HOSTS = (
    '*',
)

INSTALLED_APPS.append('debug_toolbar')

INTERNAL_IPS = (
    '127.0.0.1',
    '0.0.0.0',
)

MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')

# FOR VALIDATOR WORK
VALIDATOR_ADDRESS = str(environ.get('VALIDATOR_ADDRESS'))
VALIDATOR_NAME = str(environ.get('VALIDATOR_NAME'))
VALIDATOR_PRIVATE_KEY = str(environ.get('VALIDATOR_PRIVATE_KEY'))
PRIVATE_PASSWORD_FOR_SIGNATURE_API = str(
    environ.get('PRIVATE_PASSWORD_FOR_SIGNATURE_API')
)

# OTHER
BLOCK_RANGE = int(environ.get('BLOCK_RANGE'))
RELAYER_HTTP_URL = str(environ.get('RELAYER_HTTP_URL'))
DEFAULT_SCANNER_TIMEOUT = int(environ.get('DEFAULT_SCANNER_TIMEOUT'))
DEFAULT_SCANNER_TIMEOUT_FAST = int(environ.get('DEFAULT_SCANNER_TIMEOUT_FAST'))

MAIN_BACKEND = str(environ.get('MAIN_BACKEND'))
RELAYER_URL = str(environ.get('RELAYER_URL'))
TOKEN_API = (
    f'{MAIN_BACKEND}/api/tokens/'
    '?address={address}&network={network_title}'
)

CONTRACT_BLOCKCHAIN_IDS_TOKEN_WITH_SIX_DECIMALS = (2, 3, 4, 5, 6, 7, 8, 10, 11)

EXCLUDED_BLOCKCHAIN_IDS_FOR_SELECT = (
    0,  # NON-ACTUAL-CONTRACTS
    8,  # SOLANA
)

# TELEGRAM BOT
TELEGRAM_BACKEND_URL = environ.get('TELEGRAM_BACKEND_URL')
